### ISSUE TITLE
Tutorial files are missing

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/help#8]
The link to the Kitteh Zoo tutorial files, from the example project, 404s.

https://help.zooniverse.org/getting-started/example/#details-subject-sets-and-manifest-details-aka-what-is-a-manifest links to https://static.zooniverse.org/data.zooniverse.org/tutorial/kitteh_zoo.zip

Maybe we should upload that zip file into this repo?

**Comment by camallen** [comment]
this is a missing config on the static proxy for `data.zooniverse.org` domain paths, e.g. https://data.zooniverse.org/tutorial/kitteh_zoo.zip should serve from the data.zooniverse.org bucket path. I'll get a fix up for this soon.

**Comment by eatyourgreens** [comment]
Would it be worth moving the zip file into this repo (if possible) just so all the tutorial material is together in one place?

**Comment by camallen** [comment]
yeah feel free to make that change as well. I think the change in https://github.com/zooniverse/static/pull/185 should come in anyway and will fix the issue.
